[tasks.copy-dlls]
script = [
    "xcopy /Y \"SDL2.dll\" \"target\\release\"",
    "xcopy /Y  \"SDL2_image.dll\" \"target\\release\""
]

[tasks.copy-images]
script = "xcopy /E /I /Y \"imgs\" \"target\\release\\imgs\""

[tasks.package_zip]
script = "powershell -Command \"Compress-Archive -Path \"target\\release\\piviii.exe\", \"SDL2.dll\", \"SDL2_image.dll\", \"controller_mapping.txt\", \"imgs/\" -DestinationPath piviii.zip -Force\""

[tasks.build_release]
script = "cargo build --release"

[tasks.build]
dependencies = ["build_release", "copy-dlls", "copy-images", "package_zip"]
